type: beam_search
aggregation: mean
batch_generation: true
prompt_buffer: 500
min_step_tokens: 50
use_sequence: true
use_conclusion: true
use_thinking: true
use_verification: true
use_structure: false
use_reasoning: true
use_correction: false
