# @package _global_
evaluation:
  evaluators:
    - exact_match
  batch_evaluators:
    - llm_judge
  llm_judge:
    provider: openrouter
    model: openai/gpt-5-mini
    base_url: https://openrouter.ai/api/v1
    cache_path: ./cache/llm_judge
    n_threads: 50
    api_key: null
