# @package dataset

dataset_path: "test-time-compute/test_MATH"
dataset_split: "test"  # Dataset split to use
subset: 500  # for MATH-500 we evaluate full dataset
prompt_file: ./config/prompts/default.txt  # Path to prompt template file (optional)
answer_format: "numeric"
