# Standalone strategy config: Online Best-of-N

type: online_best_of_n
candidates_per_step: 8
min_step_tokens: 50
stop_token_ids:
  - 151645
  - 151643
max_step_tokens: 1024
use_sequence: true
use_conclusion: true
use_thinking: true
use_verification: true
use_structure: false
use_reasoning: true
use_correction: false
